version: '2.2'
services:
  adidas:
    build:
      context: ./AdidasSubscriptionService/
      dockerfile: Dockerfile
    image: adidas
    ports:
      - "8080:8080"
    networks:
      - network1
    scale: 1
    depends_on:
       - mongodb
    environment:
       - spring.data.mongodb.host=mongodb
       - email.service.host=email:8081
       - events.service.host=events:8082
    logging:
        driver: json-file

  email:
    build:
      context: ./EmailService/
      dockerfile: Dockerfile
    image: emailservice
    ports:
      - "8081:8080"
    networks:
      - network1
    scale: 1
    depends_on:
       - mongodb
    environment:
       - spring.data.mongodb.host=mongodb
    logging:
        driver: json-file
        
  events:
    build:
      context: ./EventService/
      dockerfile: Dockerfile
    image: eventservice
    ports:
      - "8082:8080"
    networks:
      - network1
    scale: 1
    depends_on:
       - mongodb
    environment:
       - spring.data.mongodb.host=mongodb
    logging:
        driver: json-file
            
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - network1

volumes:
   mongodata:
    
networks:
  network1: